---
- include_tasks:
    file: ssh_bootstrap.yml
    apply:
      tags: ["ssh"]
  when: ssh_bootstrap
  tags:
    - always

- include_tasks:
    file: ssh.yml
    apply:
      tags: ["ssh"]
  tags:
    - always
